export const categories: string[] = [
  'JavaScript',
  'All',
  'TypeScript',
  'Programming',
  'Weight Lifting',
  'Bowling',
  'Hiking',
  'React',
  'Next.js',
  'Functional Programming',
  'Object Oriented Programming',
  'Frontend Web Development',
  'Backend Web Development',
  'Web Development',
  'Coding',
];
